# Generated by Django 5.2.15 on 2026-06-28 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_group_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Outing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('location_name', models.CharField(max_length=200)),
                ('location_address', models.CharField(blank=True, max_length=500)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True)),
                ('max_attendees', models.PositiveIntegerField()),
                ('chat_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('CAN', 'Cancelled'), ('COM', 'Completed')], default='ACT', max_length=3)),
                ('creator_attending', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, to='outings.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outings.city')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.group')),
                ('interests', models.ManyToManyField(blank=True, to='users.interest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('GM', 'Group Member'), ('GU', 'Guest')], default='GU', max_length=20)),
                ('status', models.CharField(choices=[('CON', 'Confirmed'), ('PEN', 'Pending'), ('CAN', 'Cancelled')], default='CON', max_length=20)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='outings.outing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('seat', 'user')},
            },
        ),
    ]
